PLATFORM_NAME: FUN

DEFAULT_FEEDBACK_EMAIL: contact@fun-mooc.fr
DEFAULT_FROM_EMAIL: no-reply@fun-mooc.fr
TECH_SUPPORT_EMAIL: contact@fun-mooc.fr

ADMINS:
  -
    - fun-devteam
    - fun.dev@fun-mooc.fr

WIKI_ENABLED: true

TIME_ZONE: Europe/Paris

LANGUAGE_CODE: fr

# These are the languages we allow on FUN platform
# DarkLanguageConfig.released_languages must use the same codes (comma separated)
# Language codes have to match edX's ones (lms.envs.common.LANGUAGES)
LANGUAGES:
  -
    - fr
    - Français
  -
    - en
    - English
  -
    - de-de
    - Deutsch

PASSWORD_MIN_LENGTH: 8
PASSWORD_MAX_LENGTH: 30
PASSWORD_COMPLEXITY:
  UPPER: 1
  LOWER: 1
  DIGITS: 1

# Celery
CELERY_RESULT_BACKEND: djcelery.backends.database:DatabaseBackend

LTI_XBLOCK_CONFIGURATIONS:
    # Configuration for Proctor Exam xblock
  - is_launch_url_regex: false
    hidden_fields:
      - display_name
      - description
      - lti_id
      - launch_target
      - inline_height
      - accept_grades_past_due
      - ask_to_send_username
      - ask_to_send_email
      - custom_parameters
      - has_score
      - hide_launch
      - modal_height
      - modal_width
      - weight
      - button_tex
    automatic_resizing: null
    inline_ratio: 0.5625
    ignore_configuration: true
    show_button: false
    pattern: .*fun\.proctorexam\.com/lti\?id=(?P<exam_id>[0-9]+)
    defaults:
      launch_target: new_window
      lti_id: proctor_exam
  # Configuration for Marsha LTI video service
  - display_name: Marsha Video
    is_launch_url_regex: true
    pattern: .*marsha\.education/lti.*
    hidden_fields: accept_grades_past_due
      - ask_to_send_username
      - ask_to_send_email
      - button_text
      - custom_parameters
      - description
      - has_score
      - hide_launch
      - launch_target
      - modal_height
      - modal_width
      - weight
    automatic_resizing: True,
    inline_ratio: 0.5625,
    defaults:
        launch_target: iframe
        inline_height: 400
        lti_id: marsha
        launch_url: https://marsha\.education/lti/videos/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}
  # Glowbl
  - display_name: Glowbl
    is_launch_url_regex: false
    hidden_fields:
      - accept_grades_past_due
      - ask_to_send_email
      - custom_parameters
      - has_score
      - hide_launch
      - modal_height
      - modal_width
      - weight
    automatic_resizing: true
    inline_ratio: 0.5625
    defaults:
      ask_to_send_username: true
      description: |
        <img src='https://glowbl.com/wp-content/uploads/2017/04/Logo2.png'>
        <h1>Accès à la salle de visioconférence Glowbl</h1>
        <p>
        En cliquant sur ce bouton, vous quittez la plateforme <b>fun-mooc.fr</b>
        </p><p>
        En accédant à la conférence Glowbl, vous acceptez la transmission de votre nom d’utilisateur à la société Glowbl.
        </p><p>
        Attention une intervention de votre part, écrite ou vidéo, peut être enregistrée.
        </p>
      button_text: Accéder à la conférence Glowbl et accepter la transmission de mon nom d'utilisateur
      launch_target: new_window
      inline_height: 400
      lti_id: glowbl
      launch_url: https://account.glowbl.com/auth/provider/lti
  # Default LTI consumer
  - display_name: LTI consumer

######################### CMS settings #######################################

FEATURES:
  ADVANCED_SECURITY: false
  ALLOW_ALL_ADVANCED_COMPONENTS: true  # Allow all courses to use advanced components
  AUTH_USE_OPENID_PROVIDER: true
  AUTOMATIC_AUTH_FOR_TESTING: false
  CERTIFICATES_ENABLED: true
  CERTIFICATES_HTML_VIEW: true
  ENABLE_CONTENT_LIBRARIES: true
  ENABLE_COURSEWARE_INDEX: true  # index courseware content after every modification in studio
  ENABLE_CREATOR_GROUP: true  # restrain user who can create course in studio to granted ones in CourseCreator table
  ENABLE_DISCUSSION_SERVICE: true
  ENABLE_DJANGO_ADMIN_SITE: true
  ENABLE_INSTRUCTOR_ANALYTICS: true
  ENABLE_MAX_FAILED_LOGIN_ATTEMPTS: false
  ENABLE_MKTG_SITE: false
  ENABLE_S3_GRADE_DOWNLOADS: true
  ENFORCE_PASSWORD_POLICY: true
  IS_EDX_DOMAIN: true  # used to display Edx Studio logo, see edx-platform/cms/templates/widgets/header.html
  SUBDOMAIN_BRANDING: false
  SUBDOMAIN_COURSE_LISTINGS: false
  USE_CUSTOM_THEME: false

# MKTG_URLS are absolute urls used when ENABLE_MKTG_SITE is set to True
# As FUN theme is not used in CMS, we can not reverse its static pages like /tos or /privacy
MKTG_URLS:
  ROOT: http://www.fun-mooc.fr
  TOS: /tos
  PRIVACY: /privacy
